#!/bin/bash
## makes rpm package and installs it using yum

## yum install @development-tools
## yum install rpm-build rpmdevtools rpmlint mock


if [ "$UID" != "0" ] ; then
	echo "Run this script as root"
	exit 1
fi

if ! git --version ; then
	if ! dnf install git-core ; then
		echo -e "\n\nPlease install git and try again" >&2
		exit 1
	fi
fi

if ! which rpmbuild ; then
	if which dnf ; then
		dnf install rpm-build
	elif which yum ; then
		yum install rpm-build
	else
		echo "No 'dnf' nor 'yum' commands were found" >&2
		exit 1
	fi
fi

myPath="$0"
if [ "${myPath:0:2}" == "./" ] ; then
	myPath=$PWD${myPath:1}
elif [ "${myPath:0:1}" != "/" ] ; then
	myPath=$PWD/$myPath
fi


pkgName=starcal2
sourceDir="`dirname \"$myPath\"`"
"$sourceDir/scripts/assert_python2"
version=`"$sourceDir/scal2/get_version.py" | sed 's/\-/_/g'`

#echo "myPath=$myPath"
#echo "sourceDir=$sourceDir"
#echo version=$version

requires=('python(>=2.6)' 'python(<<3.0)')
requires+=('pygtk2(>=2.8)')
requires+=('pygobject2') ## The old "gobject" module
#requires+=('python-gflags')
requires+=('python-httplib2')

if [ -f "/usr/lib/$HOSTTYPE-$OSTYPE/libappindicator.so.1" ] ; then
	requires+=('python-appindicator')
fi

#recommends=()
requires+=('python-dateutil')
requires+=('python-igraph')
##requires+=('python-gnomeapplet')


recommends=()
#recommends+=('python-igraph')
#recommends+=('python-gnomevfs')

recommends+=('lxqt-openssh-askpass')
# I did not find openssh-askpass-gnome in Fedora repos

requires_str="Requires: ${requires[@]}"
recommends_str="Recommends: ${recommends[@]}"

## about "Recommends":
## https://docs.fedoraproject.org/en-US/packaging-guidelines/WeakDependencies/


echo "Name:     $pkgName
Version:        $version
Release:        1
Summary:        A full-featured international calendar written in Python

Group:          User Interface/Desktops
License:        GPLv3+
URL:            http://ilius.github.io/starcal

$requires_str
$recommends_str

BuildArch:      noarch
BuildRequires:  python3 desktop-file-utils gettext git-core

%description
StarCalendar is a full-featured international calendar written in Python,
using Gtk3-based interface, that supports Jalai(Iranian), Hijri(Islamic),
and Indian National calendars, as well as common English(Gregorian) calendar

# Turn off the brp-python-bytecompile automagic
%global _python_bytecompile_extra 0

%install
\"$sourceDir/install\" \"%{buildroot}\" --for-pkg --prefix=%{_prefix}

%post
/usr/share/starcal2/scripts/assert_python2

%files
%defattr(-,root,root,-)
%{_prefix}/share/starcal2/*
%{_prefix}/bin/starcal2*
%{_prefix}/share/applications/starcal2*
%{_prefix}/share/doc/starcal2/*
%{_prefix}/share/pixmaps/starcal2.png
%{_prefix}/share/icons/hicolor/*/apps/starcal2.png
%{_prefix}/share/locale/*/LC_MESSAGES/starcal2.mo
" > $pkgName.spec

pkgPath=`rpmbuild -bb $pkgName.spec | grep -o /usr/src/packages/RPMS/.*rpm`

if [ -z $pkgPath ] ; then
	exit 1
fi

if [ ! -f $pkgPath ] ; then
	echo "Package file $pkgPath does not exit"
	exit 1
fi

echo "Package created in \"$pkgPath\", installing"
yum remove -y $pkgName >/dev/null 2>&1
yum install --nogpgcheck "$pkgPath" ## disable gpgcheck in /etc/yum.conf
#rpm -U --force "$pkgPath" ## its OK when required packages are installed!

