#!/bin/bash
## This script builds DEB package on a debian-based distribution
## (like debian, ubuntu, mint, ...) and installs the package

function getDirTotalSize(){
	du -ks "$1" | python2 -c "import sys;print(raw_input().split('\t')[0])"
}

function installPackage(){
	pkgFile="$1"
	if [ -f /usr/bin/apt ] ; then
		if /usr/bin/apt reinstall "./$pkgFile" 2>/tmp/starcal-apt-error ; then
			return 0
		fi
		cat /tmp/starcal-apt-error
		rm /tmp/starcal-apt-error
	fi
	dpkg -i "$pkgFile" || apt-get -f install
}

if [ "$UID" != "0" ] ; then
	echo "Run this script as root" >&2
	exit 1
fi

if ! git --version ; then
	if ! apt-get install git ; then
		echo -e "\n\nPlease install git and try again" >&2
		exit 1
	fi
fi


myPath="$0"
if [ "${myPath:0:2}" == "./" ] ; then
	myPath=$PWD${myPath:1}
elif [ "${myPath:0:1}" != "/" ] ; then
	myPath=$PWD/$myPath
fi



pkgName=starcal2
sourceDir="`dirname \"$myPath\"`"
"$sourceDir/scripts/assert_python2"
version=`"$sourceDir/scal2/get_version.py"`


tmpDir=/tmp/$pkgName-install-deb
mkdir -p $tmpDir
mkdir -p "$tmpDir/DEBIAN"

"$sourceDir/install" "$tmpDir" "--for-pkg"
chown -R root "$tmpDir"
installedSize=`getDirTotalSize "$tmpDir"` ## only /usr ? FIXME

#getDirTotalSize "$tmpDir"
#getDirTotalSize "$tmpDir/usr"


depends=('python(>=2.6)' 'python(<<3.0)')
depends+=('python-gtk2(>=2.8)')
depends+=('python-gobject-2') ## The old "gobject" module
#depends+=('python-gflags')
depends+=('python-httplib2')

#if [ -f "/usr/lib/$HOSTTYPE-$OSTYPE/libappindicator.so.1" ] ; then
#	depends+=('python-appindicator')
#fi

recommends=()
recommends+=('python-dateutil')
recommends+=('python-igraph')
#recommends+=('python-gnomeapplet')
recommends+=('python-gnomevfs')
recommends+=('ssh-askpass-gnome')


depends_str=$(printf ", %s" "${depends[@]}") ; depends_str=${depends_str:2}
recommends_str=$(printf ", %s" "${recommends[@]}") ; recommends_str=${recommends_str:2}

mkdir -p $tmpDir/DEBIAN
echo "Package: $pkgName
Version: $version
Architecture: all
Maintainer: Saeed Rasooli <saeed.gnu@gmail.com>
Installed-Size: $installedSize
Depends: $depends_str
Recommends: $recommends_str
Section: Utilities
Priority: optional
Homepage: http://ilius.github.io/starcal
Description: A full-featured international calendar written in Python
 StarCalendar is a full-featured international calendar written in Python,
 using Gtk3-based interface, that supports Jalai(Iranian), Hijri(Islamic),
 and Indian National calendars, as well as common English(Gregorian) calendar
 Homepage: http://ilius.github.io/starcal
" > "$tmpDir/DEBIAN/control"

#echo "/usr/share/starcal2/scripts/assert_python2" > "$tmpDir/DEBIAN/postinst"
#chmod 755 "$tmpDir/DEBIAN/postinst"

pkgFile=${pkgName}_${version}-1_all.deb

if dpkg-deb -b "$tmpDir" "$pkgFile" ; then
	echo "Package file $pkgFile created, installing..."
	installPackage "$pkgFile"
fi

rm -Rf "$tmpDir"

